### ISSUE TITLE
Env var's persist across shell sessions

### ISSUE THREAD

**Issue by gdoenlen** [stopthatastronaut/poshdotenv#5]
I'm not sure if this is intended, but the set environment variables persist across shell sessions, this is due to using `[System.Environment]::SetEnvironmentVariable($key, $value)` if you replace that with `Set-Item "env:$key" $value` they will only persist for the current shell session.

**Comment by stopthatastronaut** [comment]
Literally just working on that before I saw this issue. Got a swathe of failing tests right now, but I'll be publishing a new release ASAP
